[package]
name = "aggregator-poc"
version = "0.1.0"
edition = "2024"

[dependencies]
# Core dependencies used directly in the code
cairo-vm = { workspace = true }
starknet_os = { workspace = true }
starknet-types-core = { workspace = true }
tokio = { workspace = true }
